### ISSUE TITLE
Setup documentation ?

### ISSUE THREAD

**Issue by Slivo-fr** [evemail/evemail#18]
Hello @ddouglas493 

I'd like to host the project on my side as I really liked it.
Could you write a quick setup how to so I can get started ?

**Comment by ddavaham** [comment]
I'll see if I can throw something together this weekend. Check back this
weekend. No promises.

**Comment by Slivo-fr** [comment]
Thanks a lot, there is no rush I'm just starting to look at it :)

**Comment by ddavaham** [comment]
https://github.com/evemail/evemail/commit/896714078328da9ae106295ba94b27edd5612e0d

Hope this helps! **Disclaimer:** None of that is tested and completely from Memory

**Comment by Slivo-fr** [comment]
Thanks a lot ! <3

**Comment by Slivo-fr** [comment]
I'm halfway through the process, few questions came to me.
Can I bypass all the mails settings (as I won't use any mail feature) ?
Is supervisor use required ? Why ?

Thanks for your help and time :)

**Comment by ddavaham** [comment]
1) Yes? I think. I would have to review the code to check but I think I can honestly say yes to that one.

I am 98% sure that by commenting out this line of code you should be able to use the application without worrying about errors from the Email Features. Obviously do not opt into email notifications on the settings page, but yeah

https://github.com/evemail/evemail/blob/master/app/Http/Controllers/MailController.php#L398

2) Technically Yes. Technically no for your use case since you do not want to be emailed. So here is the basic flow of the application outlines below:

- You sign into the application for the first time.
- The application captures your AccessToken and RefreshToken from the SSO
- These two tokens are stored in the tokens table in MySQL
- A cron job on the back-end loops through the Token table and calls on a Queue Handler to input the Token into the Queue to be called and your most recent Mail Headers Downloaded
- Supervisor runs `php artisan queue:listen` automatically without you having to be SSH'd into your server to run it manually which executes the Queue Worker that calls ESI to update the headers. Unique headers are saved to the table and the process repeats itself.

If you do not want to run Supervisor, then do not create the cron job or comment out the following line of code. 

https://github.com/evemail/evemail/blob/master/app/Console/Kernel.php#L33

**Comment by Slivo-fr** [comment]
If I understand all this right, I could replace the Supervisor by a simple cron job running `php artisan queue:listen` and the kernel line commented ?

> A cron job on the back-end loops through the Token table and calls on a Queue Handle

Could you tell me more about it ? Is it a different jobs ?

One more time, thanks for your help :)

**Comment by ddavaham** [comment]
No that would not possible.

From the ubuntu CLI you would create a cron that calls Laravel Artisan like
this

* * * * * php path/to/artisan

Artisan then tracks and makes the decision on which commands should be
executed and when. Now the task scheduler that artisan handles merely
places the job in the queue. Supervisor controls the workers and makes sure
that they keep running and executing jobs as they populate the queue.

If you want, we can meet up on Teamspeak or Slack to continue this. I am
not a fan of having a conversation like this via GitHub Issue comments.

**Comment by Slivo-fr** [comment]
Agree, let's use slack, you can find me one tweetfleet or invite me somewhere else !
